### PR TITLE
Support for WITH, INCLUDE, OPTIONAL and fixed pagination domain

### PR DESCRIPTION
**Pull request by umbreak**

### CODE REVIEW

**Comment by wwajerowicz** [comment]
retest this please

**Comment by umbreak** [comment]
retest this please

**Comment by umbreak** [comment]
retest this please

**Comment by bogdanromanx** [comment]
I think the failures are caused by the parallel test executions with Jena code. Setting the `parallelExecution in Test := false` to all modules that use jena seems to fix it, just like in #3.

**Comment by bogdanromanx** [comment]
retest this please

**Comment by bogdanromanx** [comment]
The tests fail indeed because of Jena initialization; I will merge this as is and correct the build separately.

**Pull request merged**
